//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserProfile
    {
        public int AppUserID { get; set; }
        public string LoginID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public string OtherPhone { get; set; }
        public string CNICNo { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public int AddBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
