//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int CPID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Pager { get; set; }
        public int AccountTypeID { get; set; }
        public int AccountID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
