//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_ExcelTransEntities : DbContext
    {
        public db_ExcelTransEntities()
            : base("name=db_ExcelTransEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUserProfile> AppUserProfiles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Clinic> Clinics { get; set; }
        public virtual DbSet<ContactPerson> ContactPersons { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<FileLog> FileLogs { get; set; }
        public virtual DbSet<LogType> LogTypes { get; set; }
        public virtual DbSet<Secretary> Secretaries { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Typist> Typists { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UploadedFile> UploadedFiles { get; set; }
        public virtual DbSet<Modality> Modalities { get; set; }
        public virtual DbSet<FileFaxStatu> FileFaxStatus { get; set; }
        public virtual DbSet<DictatorSecretary> DictatorSecretaries { get; set; }
        public virtual DbSet<UploadedDocument> UploadedDocuments { get; set; }
        public virtual DbSet<Dictator> Dictators { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<ManagerClinic> ManagerClinics { get; set; }
    
        public virtual int stp_SecretaryUpdate(string secretaryName, Nullable<int> dictatorID, Nullable<int> userId)
        {
            var secretaryNameParameter = secretaryName != null ?
                new ObjectParameter("SecretaryName", secretaryName) :
                new ObjectParameter("SecretaryName", typeof(string));
    
            var dictatorIDParameter = dictatorID.HasValue ?
                new ObjectParameter("DictatorID", dictatorID) :
                new ObjectParameter("DictatorID", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stp_SecretaryUpdate", secretaryNameParameter, dictatorIDParameter, userIdParameter);
        }
    
        public virtual int Proc_InsertErrorDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_InsertErrorDetails");
        }
    
        public virtual ObjectResult<stp_GetTypist_Result> stp_GetTypist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetTypist_Result>("stp_GetTypist");
        }
    
        public virtual ObjectResult<stp_GetUserLog_Result> stp_GetUserLog(Nullable<int> audioID)
        {
            var audioIDParameter = audioID.HasValue ?
                new ObjectParameter("AudioID", audioID) :
                new ObjectParameter("AudioID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetUserLog_Result>("stp_GetUserLog", audioIDParameter);
        }
    
        public virtual ObjectResult<stp_DocumentReport_Result> stp_DocumentReport(Nullable<int> dictatorID, Nullable<int> clinicID, Nullable<int> statusId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> typistAssignId)
        {
            var dictatorIDParameter = dictatorID.HasValue ?
                new ObjectParameter("DictatorID", dictatorID) :
                new ObjectParameter("DictatorID", typeof(int));
    
            var clinicIDParameter = clinicID.HasValue ?
                new ObjectParameter("ClinicID", clinicID) :
                new ObjectParameter("ClinicID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var typistAssignIdParameter = typistAssignId.HasValue ?
                new ObjectParameter("TypistAssignId", typistAssignId) :
                new ObjectParameter("TypistAssignId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_DocumentReport_Result>("stp_DocumentReport", dictatorIDParameter, clinicIDParameter, statusIdParameter, fromDateParameter, toDateParameter, typistAssignIdParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<stp_GetUploadedAudio_Result> stp_GetUploadedAudio(Nullable<int> dictatorID, Nullable<int> clinicID, Nullable<int> statusId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> typistAssignId)
        {
            var dictatorIDParameter = dictatorID.HasValue ?
                new ObjectParameter("DictatorID", dictatorID) :
                new ObjectParameter("DictatorID", typeof(int));
    
            var clinicIDParameter = clinicID.HasValue ?
                new ObjectParameter("ClinicID", clinicID) :
                new ObjectParameter("ClinicID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var typistAssignIdParameter = typistAssignId.HasValue ?
                new ObjectParameter("TypistAssignId", typistAssignId) :
                new ObjectParameter("TypistAssignId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetUploadedAudio_Result>("stp_GetUploadedAudio", dictatorIDParameter, clinicIDParameter, statusIdParameter, fromDateParameter, toDateParameter, typistAssignIdParameter);
        }
    
        public virtual ObjectResult<stp_GetUploadedAudioInfo_Result> stp_GetUploadedAudioInfo(Nullable<int> dictatorID, Nullable<int> clinicID, Nullable<int> statusId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> typistAssignId)
        {
            var dictatorIDParameter = dictatorID.HasValue ?
                new ObjectParameter("DictatorID", dictatorID) :
                new ObjectParameter("DictatorID", typeof(int));
    
            var clinicIDParameter = clinicID.HasValue ?
                new ObjectParameter("ClinicID", clinicID) :
                new ObjectParameter("ClinicID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var typistAssignIdParameter = typistAssignId.HasValue ?
                new ObjectParameter("TypistAssignId", typistAssignId) :
                new ObjectParameter("TypistAssignId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetUploadedAudioInfo_Result>("stp_GetUploadedAudioInfo", dictatorIDParameter, clinicIDParameter, statusIdParameter, fromDateParameter, toDateParameter, typistAssignIdParameter);
        }
    
        public virtual ObjectResult<stp_GetActivityLogs_Result> stp_GetActivityLogs(Nullable<int> dictatorID, Nullable<int> statusId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var dictatorIDParameter = dictatorID.HasValue ?
                new ObjectParameter("DictatorID", dictatorID) :
                new ObjectParameter("DictatorID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetActivityLogs_Result>("stp_GetActivityLogs", dictatorIDParameter, statusIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<stp_GetUserLogByDocumentId_Result> stp_GetUserLogByDocumentId(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("DocID", docID) :
                new ObjectParameter("DocID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetUserLogByDocumentId_Result>("stp_GetUserLogByDocumentId", docIDParameter);
        }
    
        public virtual ObjectResult<stp_GetDocuments_Result> stp_GetDocuments(Nullable<int> dictatorIDs, Nullable<int> clinicID, Nullable<int> typistID, Nullable<int> statusId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var dictatorIDsParameter = dictatorIDs.HasValue ?
                new ObjectParameter("DictatorIDs", dictatorIDs) :
                new ObjectParameter("DictatorIDs", typeof(int));
    
            var clinicIDParameter = clinicID.HasValue ?
                new ObjectParameter("ClinicID", clinicID) :
                new ObjectParameter("ClinicID", typeof(int));
    
            var typistIDParameter = typistID.HasValue ?
                new ObjectParameter("TypistID", typistID) :
                new ObjectParameter("TypistID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetDocuments_Result>("stp_GetDocuments", dictatorIDsParameter, clinicIDParameter, typistIDParameter, statusIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<stp_GetDocumentsData_Result> stp_GetDocumentsData(Nullable<int> dictatorID, Nullable<int> clinicID, Nullable<int> typistID, Nullable<int> statusId, Nullable<System.DateTime> dotFromDate, Nullable<System.DateTime> dotToDate, Nullable<System.DateTime> dosFromDate, Nullable<System.DateTime> dosToDate, Nullable<System.DateTime> dobFromDate, Nullable<System.DateTime> dobToDate)
        {
            var dictatorIDParameter = dictatorID.HasValue ?
                new ObjectParameter("DictatorID", dictatorID) :
                new ObjectParameter("DictatorID", typeof(int));
    
            var clinicIDParameter = clinicID.HasValue ?
                new ObjectParameter("ClinicID", clinicID) :
                new ObjectParameter("ClinicID", typeof(int));
    
            var typistIDParameter = typistID.HasValue ?
                new ObjectParameter("TypistID", typistID) :
                new ObjectParameter("TypistID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var dotFromDateParameter = dotFromDate.HasValue ?
                new ObjectParameter("DotFromDate", dotFromDate) :
                new ObjectParameter("DotFromDate", typeof(System.DateTime));
    
            var dotToDateParameter = dotToDate.HasValue ?
                new ObjectParameter("DotToDate", dotToDate) :
                new ObjectParameter("DotToDate", typeof(System.DateTime));
    
            var dosFromDateParameter = dosFromDate.HasValue ?
                new ObjectParameter("DosFromDate", dosFromDate) :
                new ObjectParameter("DosFromDate", typeof(System.DateTime));
    
            var dosToDateParameter = dosToDate.HasValue ?
                new ObjectParameter("DosToDate", dosToDate) :
                new ObjectParameter("DosToDate", typeof(System.DateTime));
    
            var dobFromDateParameter = dobFromDate.HasValue ?
                new ObjectParameter("DobFromDate", dobFromDate) :
                new ObjectParameter("DobFromDate", typeof(System.DateTime));
    
            var dobToDateParameter = dobToDate.HasValue ?
                new ObjectParameter("DobToDate", dobToDate) :
                new ObjectParameter("DobToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetDocumentsData_Result>("stp_GetDocumentsData", dictatorIDParameter, clinicIDParameter, typistIDParameter, statusIdParameter, dotFromDateParameter, dotToDateParameter, dosFromDateParameter, dosToDateParameter, dobFromDateParameter, dobToDateParameter);
        }
    
        public virtual int stp_Dictator(Nullable<int> id, Nullable<int> accountID, string systemID, string loginID, string password, Nullable<bool> allClientAccess, string prefix, string firstName, string middleName, string lastName, string gender, Nullable<int> specialityID, Nullable<bool> isSecretary, Nullable<bool> isFax, Nullable<bool> isReview, Nullable<System.DateTime> addedOn, Nullable<int> addedBy, Nullable<System.DateTime> updatedOn, Nullable<int> updatedBy, Nullable<bool> isActive, string cP_Name, string cP_Phone, string cP_Cell, string cP_Address, string cP_Email, string cP_Pager, string secretaryName, Nullable<int> noOfLine, Nullable<decimal> rateOfLine, Nullable<bool> addSign)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            var systemIDParameter = systemID != null ?
                new ObjectParameter("SystemID", systemID) :
                new ObjectParameter("SystemID", typeof(string));
    
            var loginIDParameter = loginID != null ?
                new ObjectParameter("LoginID", loginID) :
                new ObjectParameter("LoginID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var allClientAccessParameter = allClientAccess.HasValue ?
                new ObjectParameter("AllClientAccess", allClientAccess) :
                new ObjectParameter("AllClientAccess", typeof(bool));
    
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var specialityIDParameter = specialityID.HasValue ?
                new ObjectParameter("SpecialityID", specialityID) :
                new ObjectParameter("SpecialityID", typeof(int));
    
            var isSecretaryParameter = isSecretary.HasValue ?
                new ObjectParameter("IsSecretary", isSecretary) :
                new ObjectParameter("IsSecretary", typeof(bool));
    
            var isFaxParameter = isFax.HasValue ?
                new ObjectParameter("IsFax", isFax) :
                new ObjectParameter("IsFax", typeof(bool));
    
            var isReviewParameter = isReview.HasValue ?
                new ObjectParameter("IsReview", isReview) :
                new ObjectParameter("IsReview", typeof(bool));
    
            var addedOnParameter = addedOn.HasValue ?
                new ObjectParameter("AddedOn", addedOn) :
                new ObjectParameter("AddedOn", typeof(System.DateTime));
    
            var addedByParameter = addedBy.HasValue ?
                new ObjectParameter("AddedBy", addedBy) :
                new ObjectParameter("AddedBy", typeof(int));
    
            var updatedOnParameter = updatedOn.HasValue ?
                new ObjectParameter("UpdatedOn", updatedOn) :
                new ObjectParameter("UpdatedOn", typeof(System.DateTime));
    
            var updatedByParameter = updatedBy.HasValue ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var cP_NameParameter = cP_Name != null ?
                new ObjectParameter("CP_Name", cP_Name) :
                new ObjectParameter("CP_Name", typeof(string));
    
            var cP_PhoneParameter = cP_Phone != null ?
                new ObjectParameter("CP_Phone", cP_Phone) :
                new ObjectParameter("CP_Phone", typeof(string));
    
            var cP_CellParameter = cP_Cell != null ?
                new ObjectParameter("CP_Cell", cP_Cell) :
                new ObjectParameter("CP_Cell", typeof(string));
    
            var cP_AddressParameter = cP_Address != null ?
                new ObjectParameter("CP_Address", cP_Address) :
                new ObjectParameter("CP_Address", typeof(string));
    
            var cP_EmailParameter = cP_Email != null ?
                new ObjectParameter("CP_Email", cP_Email) :
                new ObjectParameter("CP_Email", typeof(string));
    
            var cP_PagerParameter = cP_Pager != null ?
                new ObjectParameter("CP_Pager", cP_Pager) :
                new ObjectParameter("CP_Pager", typeof(string));
    
            var secretaryNameParameter = secretaryName != null ?
                new ObjectParameter("SecretaryName", secretaryName) :
                new ObjectParameter("SecretaryName", typeof(string));
    
            var noOfLineParameter = noOfLine.HasValue ?
                new ObjectParameter("NoOfLine", noOfLine) :
                new ObjectParameter("NoOfLine", typeof(int));
    
            var rateOfLineParameter = rateOfLine.HasValue ?
                new ObjectParameter("RateOfLine", rateOfLine) :
                new ObjectParameter("RateOfLine", typeof(decimal));
    
            var addSignParameter = addSign.HasValue ?
                new ObjectParameter("AddSign", addSign) :
                new ObjectParameter("AddSign", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stp_Dictator", idParameter, accountIDParameter, systemIDParameter, loginIDParameter, passwordParameter, allClientAccessParameter, prefixParameter, firstNameParameter, middleNameParameter, lastNameParameter, genderParameter, specialityIDParameter, isSecretaryParameter, isFaxParameter, isReviewParameter, addedOnParameter, addedByParameter, updatedOnParameter, updatedByParameter, isActiveParameter, cP_NameParameter, cP_PhoneParameter, cP_CellParameter, cP_AddressParameter, cP_EmailParameter, cP_PagerParameter, secretaryNameParameter, noOfLineParameter, rateOfLineParameter, addSignParameter);
        }
    
        public virtual ObjectResult<GetManagers_Result> GetManagers(Nullable<int> managerID)
        {
            var managerIDParameter = managerID.HasValue ?
                new ObjectParameter("ManagerID", managerID) :
                new ObjectParameter("ManagerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManagers_Result>("GetManagers", managerIDParameter);
        }
    
        public virtual ObjectResult<GetFaxStatusFilterWise_Result> GetFaxStatusFilterWise(string clinicIDs, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string providerIDs, Nullable<int> typistID, string fileName)
        {
            var clinicIDsParameter = clinicIDs != null ?
                new ObjectParameter("ClinicIDs", clinicIDs) :
                new ObjectParameter("ClinicIDs", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var providerIDsParameter = providerIDs != null ?
                new ObjectParameter("ProviderIDs", providerIDs) :
                new ObjectParameter("ProviderIDs", typeof(string));
    
            var typistIDParameter = typistID.HasValue ?
                new ObjectParameter("TypistID", typistID) :
                new ObjectParameter("TypistID", typeof(int));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFaxStatusFilterWise_Result>("GetFaxStatusFilterWise", clinicIDsParameter, fromDateParameter, toDateParameter, providerIDsParameter, typistIDParameter, fileNameParameter);
        }
    
        public virtual ObjectResult<stp_GetDictations_Result> stp_GetDictations(string dictatorIDs, string clinicIDs, Nullable<int> typistID, Nullable<int> statusId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var dictatorIDsParameter = dictatorIDs != null ?
                new ObjectParameter("DictatorIDs", dictatorIDs) :
                new ObjectParameter("DictatorIDs", typeof(string));
    
            var clinicIDsParameter = clinicIDs != null ?
                new ObjectParameter("ClinicIDs", clinicIDs) :
                new ObjectParameter("ClinicIDs", typeof(string));
    
            var typistIDParameter = typistID.HasValue ?
                new ObjectParameter("TypistID", typistID) :
                new ObjectParameter("TypistID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetDictations_Result>("stp_GetDictations", dictatorIDsParameter, clinicIDsParameter, typistIDParameter, statusIdParameter, fromDateParameter, toDateParameter);
        }
    
        [DbFunction("db_ExcelTransEntities", "STRINGSplit_Fun")]
        public virtual IQueryable<STRINGSplit_Fun_Result> STRINGSplit_Fun(string pString, string pDelimiter)
        {
            var pStringParameter = pString != null ?
                new ObjectParameter("pString", pString) :
                new ObjectParameter("pString", typeof(string));
    
            var pDelimiterParameter = pDelimiter != null ?
                new ObjectParameter("pDelimiter", pDelimiter) :
                new ObjectParameter("pDelimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<STRINGSplit_Fun_Result>("[db_ExcelTransEntities].[STRINGSplit_Fun](@pString, @pDelimiter)", pStringParameter, pDelimiterParameter);
        }
    
        public virtual ObjectResult<stp_GetDocumentsDataNew_Result> stp_GetDocumentsDataNew(string dictatorIDs, string clinicIDs, Nullable<int> typistID, Nullable<int> statusId, Nullable<System.DateTime> dotFromDate, Nullable<System.DateTime> dotToDate, Nullable<System.DateTime> dosFromDate, Nullable<System.DateTime> dosToDate, Nullable<System.DateTime> doDFromDate, Nullable<System.DateTime> doDToDate)
        {
            var dictatorIDsParameter = dictatorIDs != null ?
                new ObjectParameter("DictatorIDs", dictatorIDs) :
                new ObjectParameter("DictatorIDs", typeof(string));
    
            var clinicIDsParameter = clinicIDs != null ?
                new ObjectParameter("ClinicIDs", clinicIDs) :
                new ObjectParameter("ClinicIDs", typeof(string));
    
            var typistIDParameter = typistID.HasValue ?
                new ObjectParameter("TypistID", typistID) :
                new ObjectParameter("TypistID", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var dotFromDateParameter = dotFromDate.HasValue ?
                new ObjectParameter("DotFromDate", dotFromDate) :
                new ObjectParameter("DotFromDate", typeof(System.DateTime));
    
            var dotToDateParameter = dotToDate.HasValue ?
                new ObjectParameter("DotToDate", dotToDate) :
                new ObjectParameter("DotToDate", typeof(System.DateTime));
    
            var dosFromDateParameter = dosFromDate.HasValue ?
                new ObjectParameter("DosFromDate", dosFromDate) :
                new ObjectParameter("DosFromDate", typeof(System.DateTime));
    
            var dosToDateParameter = dosToDate.HasValue ?
                new ObjectParameter("DosToDate", dosToDate) :
                new ObjectParameter("DosToDate", typeof(System.DateTime));
    
            var doDFromDateParameter = doDFromDate.HasValue ?
                new ObjectParameter("DoDFromDate", doDFromDate) :
                new ObjectParameter("DoDFromDate", typeof(System.DateTime));
    
            var doDToDateParameter = doDToDate.HasValue ?
                new ObjectParameter("DoDToDate", doDToDate) :
                new ObjectParameter("DoDToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_GetDocumentsDataNew_Result>("stp_GetDocumentsDataNew", dictatorIDsParameter, clinicIDsParameter, typistIDParameter, statusIdParameter, dotFromDateParameter, dotToDateParameter, dosFromDateParameter, dosToDateParameter, doDFromDateParameter, doDToDateParameter);
        }
    }
}
