//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictator()
        {
            this.Secretaries = new HashSet<Secretary>();
            this.UploadedFiles = new HashSet<UploadedFile>();
            this.UserLogs = new HashSet<UserLog>();
            this.ManagerClinics = new HashSet<ManagerClinic>();
        }
    
        public int DictatorID { get; set; }
        public int AccountID { get; set; }
        public string SystemID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public bool AllClientAccess { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int SpecialityID { get; set; }
        public bool IsSecretary { get; set; }
        public bool IsFax { get; set; }
        public bool IsReview { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public string CP_Name { get; set; }
        public string CP_Phone { get; set; }
        public string CP_Cell { get; set; }
        public string CP_Address { get; set; }
        public string CP_Email { get; set; }
        public string CP_Pager { get; set; }
        public string SecretaryName { get; set; }
        public Nullable<int> NoOfLine { get; set; }
        public Nullable<decimal> RateOfLine { get; set; }
        public Nullable<bool> AddSign { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Speciality Speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secretary> Secretaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedFile> UploadedFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerClinic> ManagerClinics { get; set; }
    }
}
