//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLog
    {
        public int LogID { get; set; }
        public int FileID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogTypeID { get; set; }
        public int UserID { get; set; }
    
        public virtual LogType LogType { get; set; }
        public virtual UploadedFile UploadedFile { get; set; }
    }
}
