//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileFaxStatu
    {
        public int ID { get; set; }
        public string FaxID { get; set; }
        public int UpDocID { get; set; }
        public int FileID { get; set; }
        public string Status { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string ToNumber { get; set; }
        public string DateCreated { get; set; }
        public string PageCount { get; set; }
        public bool IsActive { get; set; }
    }
}
