//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UploadedDocument()
        {
            this.UserLogs = new HashSet<UserLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FileID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string Extension { get; set; }
        public string Size { get; set; }
        public string Decription { get; set; }
        public Nullable<int> WordCount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int UploadBy { get; set; }
        public System.DateTime UploadOn { get; set; }
        public string Duration { get; set; }
        public Nullable<int> DocChildID { get; set; }
        public Nullable<int> CharCount { get; set; }
        public Nullable<int> CharCountWithSpace { get; set; }
        public Nullable<decimal> LineCount { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> ModalityId { get; set; }
        public string MRN { get; set; }
        public string DOB { get; set; }
        public string DOS { get; set; }
        public string RefDoctor { get; set; }
        public string FaxNumber { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual UploadedFile UploadedFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
    }
}
