//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UploadedFile()
        {
            this.FileLogs = new HashSet<FileLog>();
            this.UserLogs = new HashSet<UserLog>();
            this.UploadedDocuments = new HashSet<UploadedDocument>();
        }
    
        public int FileID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string Extension { get; set; }
        public string Size { get; set; }
        public Nullable<int> DictatorID { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public int UploadBy { get; set; }
        public System.DateTime UploadOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDownloaded { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Duration { get; set; }
        public Nullable<int> TypistId { get; set; }
        public Nullable<int> TypistAssignID { get; set; }
        public Nullable<int> StackMark { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileLog> FileLogs { get; set; }
        public virtual Status Status { get; set; }
        public virtual Typist Typist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedDocument> UploadedDocuments { get; set; }
        public virtual Dictator Dictator { get; set; }
    }
}
