//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTranscript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public Nullable<int> AudioID { get; set; }
        public Nullable<int> DocID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<int> Action { get; set; }
        public string UserLogName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserLogId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ProviderId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual UploadedFile UploadedFile { get; set; }
        public virtual UploadedDocument UploadedDocument { get; set; }
        public virtual Dictator Dictator { get; set; }
    }
}
